name: Go Build
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: "1.18"
      - name: Build
        run: go build -v ./...
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: main-executable
          path: ./main
